### ISSUE TITLE
训练好慢

### ISSUE THREAD

**Issue by giraffeGYH** [Jay-zzcoder/clip-fsac-pp#1]
训练时间好慢，是我没有配置好吗？作者大大没有给出readme，跑代码全靠自己猜~
![image](https://github.com/user-attachments/assets/3987d1a7-772f-4be8-8c6e-e8c214c89fe5)

**Comment by Jay-zzcoder** [comment]
请问你用的是什么硬件呢，我这边使用3090，100个epoch只需要一个多小时。README我会尽快写完，不好意思！

**Comment by PonyPinkPie** [comment]
> 训练时间好慢，是我没有配置好吗？作者大大没有给出readme，跑代码全靠自己猜~ ![image](https://github.com/user-attachments/assets/3987d1a7-772f-4be8-8c6e-e8c214c89fe5)

num_workers=0

**Comment by PonyPinkPie** [comment]
> 请问你用的是什么硬件呢，我这边使用3090，100个epoch只需要一个多小时。README我会尽快写完，不好意思！

`    parser.add_argument("--model", type=str, default="ViT-B-16", help="model used")
    parser.add_argument("--pretrained", type=str, default="laion400m_e32", help="pretrained weight used")
    parser.add_argument("--image_size", type=int, default=224, help="image size")`
这套配置运行是会出现越界错误，错误代码如下：
../aten/src/ATen/native/cuda/Indexing.cu:1237: indexSelectSmallIndex: block: [36,0,0], thread: [33,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "/workspace/mycode/04-ad/fsacpp/01-mytrain.py", line 710, in <module>
    result = train(args)
  File "/workspace/mycode/04-ad/fsacpp/01-mytrain.py", line 452, in train
    large_scale_tokens, mid_scale_tokens, patch_tokens, class_tokens, large_scale, mid_scale = model.encode_image(
  File "/workspace/mycode/04-ad/fsacpp/01-mytrain.py", line 268, in encode_image
    tokens_list, class_tokens, patch_tokens = self.model.encode_image(image, [large_scale, mid_scale],
  File "/workspace/mycode/04-ad/fsacpp/src/open_clip/model_revise.py", line 213, in encode_image
    features = self.visual(image, mask, proj, save_feature)
  File "/workspace/mysoftware/miniconda3/envs/fsac/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/mysoftware/miniconda3/envs/fsac/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/mycode/04-ad/fsacpp/src/open_clip/transformer.py", line 459, in forward
    class_index = torch.zeros((mask_scale.shape[0], 1), dtype = torch.int32).to(mask_scale)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
